version: '3'
services:
  php7:
    container_name: "php7"
    ports:
      - "8080:80"
    build:
        context:    "./docker/php7"
        dockerfile: "Dockerfile"
    volumes:
        - .:/var/www/html
    networks:
      db_net:
        ipv4_address: 192.168.192.2

  master_db:
    image: mysql:5.7
    container_name: "master_db"
    ports:
      - "3306:3306"
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
        - "./docker/master_db/my.cnf:/etc/mysql/conf.d/master.cnf"
        - "./docker/master_db/data/:/docker-entrypoint-initdb.d/"
    networks:
      db_net:
        ipv4_address: 192.168.192.3

  slave_db:
    image: mysql:5.7
    container_name: "slave_db"
    ports:
      - "13306:3306"
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
        - "./docker/slave_db/my.cnf:/etc/mysql/conf.d/slave.cnf"
        - "./docker/slave_db/data/:/docker-entrypoint-initdb.d/"
    networks:
      db_net:
        ipv4_address: 192.168.192.4

networks:
  db_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.192.0/24
